---
- name: rsync package
  synchronize:
    src=musicdb.deb
    dest=/tmp/musicdb.deb
    checksum=yes

- name: Stop services to avoid race conditions
  action: service
    name={{ item }}
    state=stopped
  with_items:
    - nginx
    - musicdb-celery
    - musicdb-gunicorn
  ignore_errors: yes # Permit initial installation

- name: Install package
  shell:
    dpkg -i /tmp/musicdb.deb
  ignore_errors: yes # For new dependencies

- name: Ensure dependencies
  shell:
    apt-get -f --yes install

- name: Set role
  template:
    src=role.py
    dest={{ site_packages }}/musicdb/settings/role.py

- name: Set custom/secret settings
  template:
    src=custom.py
    dest={{ site_packages }}/musicdb/settings/custom.py
  no_log: true

- name: Setup PostgreSQL user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name=musicdb

- name: Setup PostgreSQL database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name=musicdb
    owner=musicdb
    encoding=UTF-8
    template=template0

- name: collectstatic
  command:
    "{{ base_dir }}/bin/manage.py collectstatic --verbosity=2 --noinput --clear"

- name: Run migrations
  sudo: yes
  sudo_user: www-data
  shell:
    "{{ base_dir }}/bin/manage.py migrate --verbosity=2 --noinput --fake-initial 2>&1"
  register: out
  changed_when: "'No migrations to apply.' not in out.stdout"
- debug: var=out.stdout_lines

- name: Start services again
  action: service
    name={{ item }}
    state=started
  with_items:
    - musicdb-gunicorn
    - musicdb-celery
    - nginx
